Testing tic tac toe - JavaScript
gitnyasha/tic-tac-toe-javascript pull request #3
Opened 2020-06-05 22:32 UTC by gitnyasha

- the testing game logic of the game with jest

2020-06-07 20:13 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello @gitnyasha @konyan 

1. Please, you must give more details in your PR

2. There are tests that should be written
**gameBoardController**: 
- `resetBoard()` 
- `checkWinningMove()` : The test you wrote is not bad but we should see interaction between players and you should show us diagonal and vertical moves
- `hidePlayerForm()`: Show us that at the beginning of the game, the players form is hidden
- `showWinner()`: Join that test with the `checkWinningMove()` one. 

2. Read the comments below

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

2020-06-07 20:13 UTC, maelfosso commented on src/playerController.js
> +    },
There is no test concerning this method

2020-06-09 18:11 UTC, bellom commented
> * the testing game logic of the game with jest
This 👇 is an example of what @maelfosso is saying on your pull request summary
![image](https://user-images.githubusercontent.com/31897434/84183689-3207d300-aa84-11ea-9ceb-ba84b7159729.png)

2020-06-09 19:01 UTC, bellom approved these changes
## Hi @gitnyasha  :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2022-04-03 11:01 UTC, merged